---
Name: stevenpaw-sociallink
---
# SocialLink is auto-discovered as a subclass of SilverStripe\LinkField\Models\Link.

SilverStripe\Admin\LeftAndMain:
  extensions:
    - Stevenpaw\SocialLink\SocialLinkCMSExtension
