/**
 * Generates platform SVG icon files from @fortawesome/free-brands-svg-icons.
 * Output: client/dist/icons/{key}.svg  (and _fallback.svg for unmapped platforms)
 * Also generates client/dist/sociallink-cms.css with data-URI icon classes.
 */

import * as fa from '@fortawesome/free-brands-svg-icons';
import fs from 'fs';
import path from 'path';

// Maps platform keys to FontAwesome 6 Brands icon variable names.
// Platforms without a FA6 brand icon get the generic _fallback.svg.
const ICON_MAP = {
  'apple-music':  fa.faApple,
  'atlassian':    fa.faAtlassian,
  'bandcamp':     fa.faBandcamp,
  'behance':      fa.faBehance,
  'bluesky':      fa.faBluesky,
  'dailymotion':  fa.faDailymotion,
  'discord':      fa.faDiscord,
  'dribbble':     fa.faDribbble,
  'facebook':     fa.faFacebook,
  'flickr':       fa.faFlickr,
  'github':       fa.faGithub,
  'gitlab':       fa.faGitlab,
  'instagram':    fa.faInstagram,
  'kakao':        null,
  'line':         fa.faLine,
  'linkedin':     fa.faLinkedin,
  'medium':       fa.faMedium,
  'mixcloud':     fa.faMixcloud,
  'ok':           fa.faOdnoklassniki,
  'patreon':      fa.faPatreon,
  'pinterest':    fa.faPinterest,
  'reddit':       fa.faReddit,
  'reverbnation': null,
  'signal':       null,
  'skype':        fa.faSkype,
  'slack':        fa.faSlack,
  'snapchat':     fa.faSnapchat,
  'soundcloud':   fa.faSoundcloud,
  'spotify':      fa.faSpotify,
  'steam':        fa.faSteam,
  'teams':        fa.faMicrosoft,
  'telegram':     fa.faTelegram,
  'tidal':        null,
  'tiktok':       fa.faTiktok,
  'twitch':       fa.faTwitch,
  'vimeo':        fa.faVimeo,
  'vk':           fa.faVk,
  'wechat':       fa.faWeixin,
  'weibo':        fa.faWeibo,
  'whatsapp':     fa.faWhatsapp,
  'x':            fa.faXTwitter,
  'youtube':      fa.faYoutube,
  'youtube-music': fa.faYoutube,
  'zoom':         null,
  'deezer':       null,
};

// Generic fallback for platforms without a FA6 brand icon
const FALLBACK_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <path fill="currentColor" d="M307 34.8c-11.5 5.1-19 16.6-19 29.2v64H176C78.8 128 0 206.8 0 304C0 417.3 81.5 467.9 100.2 478.1c2.5 1.4 5.3 1.9 8.1 1.9c10.9 0 19.7-8.9 19.7-19.7c0-7.5-4.3-14.4-9.8-19.5C108.8 431.9 96 414.4 96 384c0-53 43-96 96-96h96v64c0 12.6 7.4 24.1 19 29.2s25 3 34.4-5.4l160-144c6.7-6.1 10.6-14.7 10.6-23.8s-3.8-17.7-10.6-23.8l-160-144c-9.4-8.5-22.9-10.6-34.4-5.4z"/>
</svg>`;

function buildSVG(icon) {
  const [width, height, , , pathData] = icon.icon;
  const paths = Array.isArray(pathData) ? pathData : [pathData];
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">\n  ${paths.map(d => `<path fill="currentColor" d="${d}"/>`).join('\n  ')}\n</svg>\n`;
}

export function generateIcons(outDir) {
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, '_fallback.svg'), FALLBACK_SVG);

  for (const [key, icon] of Object.entries(ICON_MAP)) {
    const svg = icon ? buildSVG(icon) : FALLBACK_SVG;
    fs.writeFileSync(path.join(outDir, `${key}.svg`), svg);
    console.log(`  ✓ ${key}.svg${icon ? '' : ' (fallback)'}`);
  }
}

function encodeSVGForCSS(svg) {
  return svg
    .replace(/\n/g, ' ')
    .replace(/\s+/g, ' ')
    .replace(/"/g, "'")
    .replace(/%/g, '%25')
    .replace(/#/g, '%23')
    .replace(/</g, '%3C')
    .replace(/>/g, '%3E')
    .replace(/&/g, '%26')
    .trim();
}

function iconClass(selector, svg) {
  const uri = encodeSVGForCSS(svg);
  return `${selector}::before {
  font-family: initial !important;
  content: '' !important;
  background: url("data:image/svg+xml,${uri}") no-repeat center / contain;
  display: inline-block;
  width: 1.1em;
  height: 1.1em;
  vertical-align: -0.2em;
}`;
}

export function generateCMSCSS(iconsDir, outFile) {
  const classes = [
    '/* Auto-generated by silverstripe-sociallink – do not edit */',
    iconClass('.font-icon-social-link', FALLBACK_SVG),
  ];

  for (const [key, icon] of Object.entries(ICON_MAP)) {
    const svg = icon ? buildSVG(icon) : FALLBACK_SVG;
    classes.push(iconClass(`.font-icon-social-link-${key}`, svg));
  }

  fs.writeFileSync(outFile, classes.join('\n\n') + '\n');
  console.log(`  ✓ sociallink-cms.css (${classes.length - 1} platform classes)`);
}
